---
- name: Instalando MySQL
  apt: name={{ item }} state=installed
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client

- name: Iniciando servicio de MySQL
  service: name=mysql state=started

- name: Cambiando contraseña de root
  mysql_user: name=root password={{ password }} host=localhost priv=*.*:ALL,GRANT state=present

- name: Copiando my.cnf del usuario root.
  template: src=my.conf dest=/root/.my.cnf owner=root mode=0600

- name: Habilitando el acceso desde otra maquinas
  lineinfile: path=/etc/mysql/mysql.conf.d/mysqld.cnf regexp='^bind-address*' line='bind-address	= 0.0.0.0'

- name: Reiniciando servicio de MySQL
  service: name=mysql state=restarted

- name: Creando base de datos de aplicación
  mysql_db: name={{ ddbb }} state=present collation=utf8_general_ci

- name: Copiando en el servidor datos iniciales
  copy: src=app-dump.sql dest=/tmp/dump.sql

- name: Cargar datos iniciales
  shell: cat /tmp/dump.sql | mysql -u root -p{{ password }} {{ ddbb }}

- name: Creando usuario de aplicación
  mysql_user: name={{ web_user }} password={{ password }} host={{ web }} priv=app.*:SELECT,INSERT,UPDATE,DELETE state=present
